apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: drone
spec:
  selector:
      matchLabels:
        app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: nginx
          image: phpmyadmin/phpmyadmin
          env:
            - name: PMA_ARBITRARY
              value: "1"
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: drone
  labels:
    apps: phpmyadmin
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
  selector:
    app: phpmyadmin
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: phpmyadmin
  namespace: drone
spec:
  rules:
    - host: "phpmyadmin.interrobang.consulting"
      http:
        paths:
          - backend:
              serviceName: phpmyadmin
              servicePort: http
