apiVersion: v1
kind: Secret
metadata:
  name: drone
  namespace: drone
data:
  drone-github-client: ${base64_drone_github_client}
  drone-github-secret: ${base64_drone_github_secret}
  drone-secret: ${base64_drone_secret}
  drone-database-source: ${base64_drone_database_source}
