apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: drone
  namespace: drone
spec:
  selector:
      matchLabels:
        app: drone
  replicas: 1
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
        - name: drone
          image: drone/drone:${drone_tag}
          env:
            - name: DRONE_OPEN
              value: "${drone_open}"
            - name: DRONE_ADMIN
              value: "${drone_admin}"
            - name: DRONE_HOST
              value: "https://drone.${domain}"
            - name: DRONE_GITHUB
              value: "true"
            - name: DRONE_GITHUB_CLIENT
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: drone-github-client
            - name: DRONE_GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: drone-github-secret
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: drone-secret
            # - name: DRONE_DATABASE_DRIVER
            #   value: "mysql"
            # - name: DRONE_DATABASE_DATASOURCE
            #   valueFrom:
            #     secretKeyRef:
            #       name: drone
            #       key: drone-database-source
          ports:
            - containerPort: 80
              name: drone-http-port
            - containerPort: 9000
          volumeMounts:
            - name: drone-sqlite-db
              mountPath: /var/lib/drone
      volumes:
        - name: drone-sqlite-db
          gcePersistentDisk:
            pdName:  drone-sqlite-db
            fsType: ext4
