apiVersion: v1
kind: Service
metadata:
  name: drone
  namespace: drone
  labels:
    apps: drone
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30041
    - name: agent
      port: 9000
  selector:
    app: drone